# Change these first
owner: ot-tech-code # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: OT Tech
    url: https://ottech.biz/
  - name: BizApps
    url: https://bizapps.pro/
  - name : RSA
    url: $ENDPOINT_RSA
assignees:
  - subran
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.bizapps.pro
  #baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/ot-tech-code/status/master/assets/OT-Logo.png
  name: Status
  introTitle: "**OT Tech Status**"
  introMessage: Monitor the real-time availability, performance, and uptime of OT Tech applications and services. This status page provides live incident updates, maintenance notifications, and historical uptime metrics to keep you informed about the health of our platforms.
  #navbar:
  #  - title: Status
  #    href: /
  #  - title: GitHub
  #    href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
